---
name: "Movie subtitle sorter"
guid: "786e0827-ed4b-4cbc-870b-12c186f47894"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Short description about your plugin"
description: >
  Looks for through all MOVIE libraries for subtitles hidden in subfolders and copies them with a working name.
category: "Library"
owner: "BennyStarfighter"
artifacts:
- "Jellyfin.Plugin.SubtitleFixer.dll"
changelog: >
  changelog
