---
name: "Movie subtitle sorter"
guid: "786e0827-ed4b-4cbc-870b-12c186f47894"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net6.0"
overview: "Copies subtitles from subfolders to movie folder."
description: >
  Looks through all MOVIE libraries for subtitles hidden in subfolders and copies them with a working name.
category: "Library"
owner: "BennyStarfighter"
artifacts:
- "Jellyfin.Plugin.SubtitleFixer.dll"
changelog: >
  changelog
